import './globals.css'
import PrintQueue from './components/PrintQueue'

export const metadata = {
  title: 'Formatic Fobs',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex w-screen h-screen px-12 pt-12 pb-14">
          <div className="w-3/4 rounded-3xl bg-black text-4xl outline-none shadow-lg shadow-white border border-white font-gridularRegular relative">
            <div className="w-full h-28 px-8 py-4 bg-gradient-to-b from-black from-50% to-transparent absolute top-0 left-0 z-10 rounded-3xl">
              <p className="text-7xl"><span className="font-copula">formatic</span><span className="font-waffold">FOBS</span></p>
            </div>
            {children}
          </div>
          <div className="flex flex-col items-center justify-center w-12">
            <svg class="h-full w-10">
              <defs>
                <marker
                  id="arrow"
                  viewBox="0 0 10 10"
                  refX="5"
                  refY="5"
                  markerWidth="6"
                  markerHeight="6"
                  orient="auto-start-reverse">
                  <path d="M 0 0 L 10 5 L 0 10 z" fill="#fff" />
                </marker>
              </defs>
              <line x1="18" y1="5" x2="18" y2="99%" stroke="#fff" stroke-width="1.5" stroke-dasharray="2,3"  marker-end="url(#arrow)" marker-start="url(#arrow)"/>
            </svg>
          </div>
          <div className="w-1/4 rounded-3xl p-5 bg-black text-4xl outline-none shadow-lg shadow-white border border-white font-gridularRegular lowercase text-center">
            <PrintQueue/>
          </div>
        </div>
      </body>
    </html>
  )
}
